### PR TITLE
correct URL to get API credentials.

### PR DESCRIPTION
**Pull request by fiatjaf**
see https://github.com/jaybryant/paypal-recurring/issues/3

### CODE REVIEW

**Comment by uncedric** [comment]
the actual URL seems to be working well on my end, why do you think we should switch? maybe we should add more instructions about what to do once you login as a developer, what do you think?

**Comment by fiatjaf** [comment]
The current URL points to the home page of the Paypal Developer portal, not to the actual place where the sandbox credentials are (also, the credentials are not only sandbox credentials, they are "real" credentials from fake users that only exist in the sandboxed world, that is not so straightforward, Paypal doesn't explain these things very well).

Also, the "live" credentials, as I could understand are in https://www.paypal.com/us/cgi-bin/webscr?cmd=_profile-api-signature, the link I've sent in the commit. Right? Or for you the live credentials are at the home page of the Paypal Developer portal?

**Comment by fiatjaf** [comment]
Not so much related to this, but clarify me one thing, please: if everything works (and it really seens to work) just by using your library and inputing the credentials we get on the link, why is there a process for submitting and approval of apps in the Paypal Developer portal? Do you know anything about this?

**Comment by uncedric** [comment]
> The current URL points to the home page of the Paypal Developer portal, not to the actual place where the sandbox credentials are (also, the credentials are not only sandbox credentials, they are "real" credentials from fake users that only exist in the sandboxed world, that is not so straightforward

When I click that URL I go directly to paypal login, once I login I am redirected to my personal dashboard, what I was telling you in other thread is that we should explain: 
1. first login here (our current URL) 
2. and then go to this link (the LINK you mention)  

>  if everything works (and it really seens to work) just by using your library and inputing the credentials we get on the link, why is there a process for submitting and approval of apps 

I think that is for special paypal features, I didn't followed that process :smile:

**Comment by fiatjaf** [comment]
I understand. You are right. Thank you.

**Pull request closed without merging**
